# Generated by Django 5.2.3 on 2025-09-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gymApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymbranch",
            name="location",
            field=models.CharField(
                choices=[("59", "Sector 59"), ("7", "Phase 7")],
                default="Phase 7",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gymbranch",
            name="name",
            field=models.CharField(
                choices=[("Golden", "Golden Gym"), ("Jora", "Jorawar Fitness")],
                default="Jora",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duration_months",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 month"),
                    (3, "3 months"),
                    (6, "6 months"),
                    (12, "12 months"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                    ("pro", "Pro"),
                ],
                default="basic",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
