# Generated by Django 5.2.3 on 2025-09-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trainer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("yoga", "Yoga"),
                    ("strength", "Strength Training"),
                    ("cardio", "Cardio"),
                    ("crossfit", "CrossFit"),
                    ("pilates", "Pilates"),
                ],
                default="strength",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="VideoTutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="video_thumbnails/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Trainer.trainer",
                    ),
                ),
            ],
        ),
    ]
