# Generated by Django 5.2.3 on 2025-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trainer", "0002_alter_trainer_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="trainers/profile_pictures/default.png",
                null=True,
                upload_to="trainers/profile_pictures/",
            ),
        ),
    ]
