# Generated by Django 5.2.3 on 2025-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trainer", "0004_alter_trainer_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="https://lnbamhwkbhfxoeltsoqt.supabase.co/storage/v1/object/public/media-files/trainers/profile_pictures/default.png",
                max_length=500,
                null=True,
                upload_to="trainers/profile_pictures/",
            ),
        ),
    ]
