# Generated by Django 5.2.3 on 2025-09-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trainer", "0005_alter_trainer_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="https://utpzvsvgktqppalcpvkn.supabase.co/storage/v1/object/sign/GymApp/media/default.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV9iNWEwNDA3MS1iNTU5LTRmYzMtYjZhOC02MTZjMGI4OTE3NDkiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJHeW1BcHAvbWVkaWEvZGVmYXVsdC5wbmciLCJpYXQiOjE3NTc1MjY3NzcsImV4cCI6MTc4OTA2Mjc3N30.1VfW6hH7TfAFcQtz2YzwxMiy9Ldj9domHDSMaspN91w",
                max_length=500,
                null=True,
                upload_to="trainers/profile_pictures/",
            ),
        ),
    ]
