# Generated by Django 5.2.3 on 2025-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Member",
            "0003_payment_currency_payment_order_id_payment_payment_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="trainers/profile_pictures/default.png",
                null=True,
                upload_to="Members/profile_pictures/",
            ),
        ),
    ]
